{{- if .Values.quantanexus.enabled  }}
apiVersion: v1
kind: Service
metadata:
  name: nginx-reverse-proxy
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "quantanexus.labels" . | nindent 4 }}
spec:
  selector:
    app: nginx-reverse-proxy
  ports:
  - protocol: TCP
    port: {{ .Values.quantanexus.nginx.port }}
    targetPort: {{ .Values.quantanexus.nginx.port }}
  type: ClusterIP
{{- end }}