{{- if .Values.global.createNamespace }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.global.namespace }}
  labels:
    name: {{ .Values.global.namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-20"
    "helm.sh/hook-delete-policy": before-hook-creation
{{- end }}
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    hw.ns.usage: user
    kubernetes.io/metadata.name: qnsystemdefaultnamespace
  name: qnsystemdefaultnamespace
spec:
  finalizers:
    - kubernetes
