apiVersion: v1
kind: ConfigMap
metadata:
  name: abc-experiment-service-config
  namespace: abc-platform
data:
  service.conf: |
    #本文件是配置文件，链接docker和kubernetes
    [Docker]
    docker_base_url=https://172.17.0.1:8088
    
    docker_cert = /etc/abc_platform/docker-ssl/client-cert.pem
    docker_key =  /etc/abc_platform/docker-ssl/client-key.pem
    docker_ca_cert = /etc/abc_platform/docker-ssl/ca.pem
    
    #k8s的配置文件，链接K8s APIService 服务
    [Kubernetes]
    #优先采用配置文件的方式，如果不采用配置文件，则采用后边的参数host,ssl_ca_cert,verify_ssl,token,assert_hostname 等
    # kube_config_file=96_admin.conf
    kube_config_file=/etc/kubernetes/admin.conf
    # kube_config_file=F:/DEV/odoo_original_14.0/odoo/debian/localhost_admin.conf
    # api-server地址
    kube_host= https://172.17.0.1:6443
    # 指定CA证书
    kube_ssl_ca_cert = /etc/kubernetes/pki/ca.crt
    # 启用证书验证,URL和IP都会被验证，一般不启用
    kube_verify_ssl = False
    kube_token = {{$token}}
    kube_assert_hostname = portal
    [Service]
    port=8075
    host=0.0.0.0
    virt_vnc_node=192.168.103.170
    virt_vnc_port=32211
    enable_auth=false
    auth_url_base=http://auth1.hi168.com:31069/vue/user/auth
  admin.conf: |
    apiVersion: v1
    clusters:
    - cluster:
        certificate-authority-data: {{$DATA}}
        server: https://192.168.103.151:6443
      name: cluster1
    contexts:
    - context:
        cluster: cluster1
        user: admin
      name: context-cluster1
    current-context: context-cluster1
    kind: Config
    preferences: {}
    users:
    - name: admin
      user:
        client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUQyakNDQXNLZ0F3SUJBZ0lVR2g5bFMydStXM1NBOUJpQXd2ZGhNK0RscVlvd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1pERUxNQWtHQTFVRUJoTUNRMDR4RVRBUEJnTlZCQWdUQ0VoaGJtZGFhRzkxTVFzd0NRWURWUVFIRXdKWQpVekVNTUFvR0ExVUVDaE1EYXpoek1ROHdEUVlEVlFRTEV3WlRlWE4wWlcweEZqQVVCZ05WQkFNVERXdDFZbVZ5CmJtVjBaWE10WTJFd0lCY05NalV3T1RFd01EWXpPVEF3V2hnUE1qQTNOVEE0TWprd05qTTVNREJhTUdjeEN6QUoKQmdOVkJBWVRBa05PTVJFd0R3WURWUVFJRXdoSVlXNW5XbWh2ZFRFTE1Ba0dBMVVFQnhNQ1dGTXhGekFWQmdOVgpCQW9URG5ONWMzUmxiVHB0WVhOMFpYSnpNUTh3RFFZRFZRUUxFd1pUZVhOMFpXMHhEakFNQmdOVkJBTVRCV0ZrCmJXbHVNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXVzYU1WQ05rUFdZWVlkWjcKU0plNEV5bXBpU1FwSnlHNEtDQzBzQ0xaSU9yZXd2K0VlTGtUcGxCVStvM0tscldVOCtxOHdzTzJCUzlzejY5Zwp5eUVrdVdWK1ZKUzloZTNtZ09tNjcxckxlMzY0OG5XSkVCNnBDcyt6UG8rZVp6blVHY3dBajM5NHFJR2VrNmNhCnJ2L09SQU9QWWRlOStEeDdKK1VKQnlTUUg5a3NJL2ZGaUZhV3JmOWdLaVpPTGlMWGZPU2w5dU9xeFh3NTdGRWEKOWVFTWdYS0hxK1E2WEVYbkVkaGRUQ3hNMDFORzJjTnlkdDh1cnpzS1dsNFp3TUdZekxNZnBQdE0vOFJmWktoWApuelgwdURJQ2pBSkhLY09oeStpanBIaXpzV3diNmZtNDkxbk14bEpENk93cWRtUTJnUnRBdlRBY3dzQlN6MXdyCmt5YVNyd0lEQVFBQm8zOHdmVEFPQmdOVkhROEJBZjhFQkFNQ0JhQXdIUVlEVlIwbEJCWXdGQVlJS3dZQkJRVUgKQXdFR0NDc0dBUVVGQndNQ01Bd0dBMVVkRXdFQi93UUNNQUF3SFFZRFZSME9CQllFRk95SWJxV0RYdXF6eFZmMAphanZMK2J2MjhHbENNQjhHQTFVZEl3UVlNQmFBRkZTQisvb0wxdklJWGs0OEFQQUVuYXJOc1ZBYk1BMEdDU3FHClNJYjNEUUVCQ3dVQUE0SUJBUUNpZjJONjZ1WURpRTJyWHV4QlI5YWRhSmlTSURDY2JUelVlc1ZjUytiREprNWIKM3lNdDkwOTMycmhFaEMrbk1FakEwSTNhMFZMaGtxa2ROTmRtb0dFRkVVTE1aUjNsRnR6L3Z4Wng4M1NaRTEwYQpCaElDNExOMHBkdllCUW91ZUxjWGZ4Wm9VRjhGSEZPeCthdk5EM1NTbzhvcWE1dUVVTkhwZnB5UUVLUHV1ZTF0Cll2eTZtMnlTTUhkbTIreHhXeTQyWXNjMXJhaTNpcFhQbVo1T2kzLzc0MTJqbHZDMHhldW9JSXZobGhYUFdGbjcKRitsRkpNeDNFU0luVWVaSTh3VTFObklSMldBdlEzTUhEWEcwOGt6ek9wV0lES2FxTUR3clduV1pmc3V5OVFPeQppTDNYK2ZqVFpxS3VnNDlUMnR1d1ZGa095TkkxM3VScThzQjJwYTN5Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
        client-key-data: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBdXNhTVZDTmtQV1lZWWRaN1NKZTRFeW1waVNRcEp5RzRLQ0Mwc0NMWklPcmV3ditFCmVMa1RwbEJVK28zS2xyV1U4K3E4d3NPMkJTOXN6NjlneXlFa3VXVitWSlM5aGUzbWdPbTY3MXJMZTM2NDhuV0oKRUI2cENzK3pQbytlWnpuVUdjd0FqMzk0cUlHZWs2Y2Fydi9PUkFPUFlkZTkrRHg3SitVSkJ5U1FIOWtzSS9mRgppRmFXcmY5Z0tpWk9MaUxYZk9TbDl1T3F4WHc1N0ZFYTllRU1nWEtIcStRNlhFWG5FZGhkVEN4TTAxTkcyY055CmR0OHVyenNLV2w0WndNR1l6TE1mcFB0TS84UmZaS2hYbnpYMHVESUNqQUpIS2NPaHkraWpwSGl6c1d3YjZmbTQKOTFuTXhsSkQ2T3dxZG1RMmdSdEF2VEFjd3NCU3oxd3JreWFTcndJREFRQUJBb0lCQUdtdkRScFN5RmFCbll4Rwp5NDJBNDlSYi82VXRBK2d6aVR1VGZnb29QY29GZkRURVZsWGxDM3hRK2pTbjVKa3dkKzhveE5SRDM0dkJrUVZYClRDTEVSejVzY25Zemo2WG52a1QxZkNRUnNRL1kzWmU3NytsaUgrNlJKZkJoWFpVMVFKRzBRQ0R5VlBpc0YybWUKNVZkZVFYMTBzajMvMEd0VTlhN1dSeXgyZ09LemkxOE5mRk41eWZhMS9RZ3FQR2E3R0l4MGR1TFBXV1h2NmpjawoyZVkxVExwMFduYkJrcVUvZDhMelpHZnV0elF2U3NrQXIrUUNuMWdRNjM1TVI0SjVWUTlmQitjbTJPS1NHQy9zCkwyVkV6QTZRdWFJNXBPNDJnd2hXcHlOeXltRjVxM3RFd0I2YktkVUQ5WUtna0RoZkEyakRIOE5zOURhZE1RU2EKOUxjMlprRUNnWUVBK090UUM2NGZ6WVpSWWsvMCs5TVFqZmc4SWxQY3FDWmZudEIxdy9zS01tYUVqRXFYZzlxNwp3YXd1ZzE5dURmZVYvRTJtek0vZmFxTmNIZlpuaGoydUdDOGw0RUJPdm5mUEpOV2ViUDR2Z0F5cjJaSWEyUjFpClZTUGp0OGU1L3dVNFo3TGFnRytIZGJqWVIrUEduOTh4OEJ4Ty95bHRBTERVVWFtT0MrT1ZEYUVDZ1lFQXdCYXcKOTVIQk9XTTNGckpicGs4QitQSEdHWmRmYlkrRmlYb2ZhZ293N2F2VkJRdEw0MzF4OHhGMkZIaDEvSUtaVDRzWgp5aS81TklGa25JWHQvVnR1VExDYXhzWjB2RC9vTFEvNmZmZEJNZDZ4bmFVQThhSzcyWjVaaFFWcDN1S2tZQXlSClRlVHJYS24xUXlmck1kSGZ1MjNmU1FrNEZ6OWJoS2NPN2xUK25rOENnWUVBcjB5NUFLRE9FT1hKSnQxOGdHU3kKUWVsU0lETERNVUJsRXVsb0ptOERUVjlaZFp1S2ZQZHNSd2JGY3d1ZjdBSXpCSTZESzdZeGQxNDRuM2xLaXdXaApON0xzajdONlFUVUxFcnZHYUtmU04vRzBqUE1TS1ZsQ1NRZVBkWHdaQnZwY01OdUtlZTBSanR4d3BLQkszNGhHCkdQMDJ2UWdsbGRqeWpkaEZDeVpwY0VFQ2dZQkI2d2VMemM3N1BKcjVCUGdDbUhaYTBjMWpsdGkrcGxQekc1K1EKS2pNa1BLVjdkNmJ4U0dsRU9xZkUycG5TcjVhZy8yRTRTMEkvekcrVWJ6bCtpbFBOcVlWVDFXTFYvekJUMW5ubApwR1lSRVJUdXZtTVdpUHZoOEQ5VU1NbG1IV3kvTVZEajVEMElyYUpuQzFuZzNON2tXUTRZNkRzQmIxS2VzUjJrCm1ESlFiUUtCZ1FDbmR6dVNYczlnU2NWOUJFS01DdThoa0Q2TkUrK1V6WUFUekdnVzlNY3dramREeW1OY0hadDkKcGVNOUJlWjF5WUdqZFU3aWxDL1NCNzZMRUpmUm1CZjhscUg5SEZVYTlSWmFXa0dsZnBPSXpFVzFnRU03YUhWTQozejBKV1JKSWphLzBRNTdkZ1NwZzFwdEhsa1Vkc1BXRElYSVZtZXd5SmM2ejN4UzhtUVg3cHc9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
  pre-start.sh: |
    echo "abc-experiment-service pre-start.sh called"
    mkdir -p /etc/kubernetes/
    mkdir -p /etc/abc_platform/docker-ssl
    cp /etc/abc-experiment-service/service.conf ${ABC_EXP_SERVICE}/service.conf
    cp /etc/abc-experiment-service/admin.conf /etc/kubernetes/admin.conf
    echo "abc-experiment-service pre-start.sh called finish"
