{{- if .Values.components.abcUploader }}
apiVersion: v1
kind: Secret
metadata:
  name: kube-uploader-conf
  namespace: {{ .Values.global.namespace | default "abc-platform" }}
type: Opaque
stringData:
  app.conf: |-
    #beego配置项，为空表示false，不配置这个选项为false
    appname = {{ .Values.abcUploader.config.appname }}
    httpport = {{ .Values.abcUploader.config.httpport }}
    # 产品模式提高性能  dev模式增强错误输出
    runmode = "{{ .Values.abcUploader.config.runmode }}"
    # 如果配置了kubeconfig 则默认表示使用kubeconfig default:false or ""
    kubeconfig = {{ .Values.abcUploader.config.kubeconfig }}
    # 配置是否打开pprof  default:false
    beego.pprof = {{ .Values.abcUploader.config.beego_pprof }}
    # 允许跨域  default:false
    beego.enable_allow_origin = {{ .Values.abcUploader.config.enable_allow_origin }}
    # 配置是否开启https
    https = {{ .Values.abcUploader.config.https }}
    # 配置是否开启 nginx反向代理url前缀
    url_prefix={{ .Values.abcUploader.config.url_prefix }}
    # 配置是否打开demo页面
    enable_demo = {{ .Values.abcUploader.config.enable_demo }}
    #是否打开debug 为空表示默认info
    debug = {{ .Values.abcUploader.config.debug }}
    # uploader 上传根目录 默认./upload 允许的格式举例： /var/upload  ./myupload /var/upload/  f:\\dev f:/dev/upload 等
    uploader_home= {{ .Values.abcUploader.config.uploader_home }}
    #database 配置 default:false
    orm.debug = {{ .Values.abcUploader.config.orm_debug }}
    # 多少小时清理一下chunk
    clean_chunk_duration = {{ .Values.abcUploader.config.clean_chunk_duration }}
    # Sqlite 数据库存放位置
    sqlite_db_path= {{ .Values.abcUploader.config.sqlite_db_path }}
{{- end }}