{{- if and .Values.abcWebShell.enabled .Values.abcWebShell.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: abc-webshell-ingress
  namespace: {{ .Values.global.namespace | default "quantanexus" }}
  labels:
    app: abc-webshell
    {{- include "quantanexus.labels" . | nindent 4 }}
  
  annotations:
    kubernetes.io/ingress.class: nginx
    {{- range $key, $value := .Values.abcWebShell.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
    {{- if and .Values.certManager.enabled (not .Values.ingress.tlsManual) }}
    cert-manager.io/cluster-issuer: {{ .Values.certManager.issuerName }}
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    {{- end }}    
spec:
  ingressClassName: {{ .Values.abcWebShell.ingress.className }}
  rules:
    - host: {{ include "quantanexus.domainName" . }}
      http:
        paths:
          {{- range .Values.abcWebShell.ingress.paths }}
          - pathType: Prefix
            path: {{ . }}
            backend:
              service:
                name: abc-webshell
                port:
                  number: 80
          {{- end }}
  {{- if .Values.abcWebShell.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ include "quantanexus.domainName" . }}
      secretName: {{ .Values.abcWebShell.ingress.tls.secretName }}
  {{- end }}
{{- end }}