---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    hw.ns.usage: user
    kubernetes.io/metadata.name: qnsystemdefaultnamespace2
  name: qnsystemdefaultnamespace2
spec:
  finalizers:
    - kubernetes
