{{- if .Values.components.abcWebShell  }}
apiVersion: v1
items:
- apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    annotations:
      nginx.ingress.kubernetes.io/cors-allow-headers: DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization
      nginx.ingress.kubernetes.io/cors-allow-methods: PUT, GET, POST, OPTIONS
      nginx.ingress.kubernetes.io/cors-allow-origin: '*'
      nginx.ingress.kubernetes.io/enable-cors: "true"
      nginx.ingress.kubernetes.io/rewrite-target: /$1
      nginx.ingress.kubernetes.io/service-weight: ""
    name: abc-webshell-ingress-patch
    namespace: {{ .Values.global.namespace }}
  spec:
    ingressClassName: nginx
    rules:
    - host: {{ .Values.global.domainName }}
      http:
        paths:
        - backend:
            service:
              name: abc-webshell
              port:
                number: 80
          path: /tpatch/(.*)
          pathType: Prefix
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
{{- end }}