apiVersion: v1
items:
- apiVersion: v1
  data:
    tls.crt: {{$cert}}
    tls.key: {{$CERT}}
  kind: Secret
  metadata:
    annotations:
      cert-manager.io/alt-names: '*.qntest001.hi168.com'
      cert-manager.io/certificate-name: abc-tls-hwua-common-4
      cert-manager.io/common-name: '*.qntest001.hi168.com'
      cert-manager.io/ip-sans: ""
      cert-manager.io/issuer-group: ""
      cert-manager.io/issuer-kind: ClusterIssuer
      cert-manager.io/issuer-name: letsencrypt
      cert-manager.io/uri-sans: ""
    creationTimestamp: "2025-09-10T09:34:27Z"
    name: abc-tls-hwua-common-4
    namespace: abc-platform
    resourceVersion: "403662759"
    uid: ac9ac3bc-cee3-4b78-8cb2-a1efc0806aec
  type: kubernetes.io/tls
- apiVersion: v1
  data:
    tls.crt: {{}}
    tls.key: {{}}
  kind: Secret
  metadata:
    annotations:
      cert-manager.io/alt-names: {{}}
      cert-manager.io/certificate-name: {{}}
      cert-manager.io/common-name: qntest001.hi168.com
      cert-manager.io/ip-sans: ""
      cert-manager.io/issuer-group: ""
      cert-manager.io/issuer-kind: ClusterIssuer
      cert-manager.io/issuer-name: letsencrypt
      cert-manager.io/uri-sans: ""
    creationTimestamp: "2025-09-10T09:33:05Z"
    name: abc-tls
    namespace: abc-platform
    resourceVersion: "403661970"
    uid: d1a1cdc7-fcfd-4b01-81ce-17155d1bb985
  type: kubernetes.io/tls
kind: List
metadata:
  resourceVersion: ""
