apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
  namespace: {{ .Values.namespace.name }}
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
data:
  message: {{ .Values.app.message | quote }}
  environment: {{ .Values.app.environment | quote }}
  namespace: {{ .Values.namespace.name | quote }}