{{- if .Values.quantanexus.enabled }}
{{- if .Values.quantanexus.nginx.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: nginx-reverse-proxy
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: nginx-reverse-proxy
  ports:
  - protocol: TCP
    port: {{ .Values.quantanexus.nginx.port }}
    targetPort: {{ .Values.quantanexus.nginx.port }}
  type: ClusterIP
{{- end }}
{{- end }}