{{- if .Values.quantanexus.enabled  }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-reverse-proxy
  namespace: {{ .Release.Namespace }}
  labels:
    app: nginx-reverse-proxy
    {{- include "quantanexus.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-reverse-proxy
  template:
    metadata:
      labels:
        app: nginx-reverse-proxy
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: mgr-worker-node
                operator: Exists
      initContainers:
      - name: data-init-container
        image: {{ .Values.global.registry }}/{{ .Values.quantanexus.nginx.frontend.repository }}:{{ .Values.quantanexus.nginx.frontend.tag }}
        imagePullPolicy: {{ .Values.quantanexus.app.imagePullPolicy }}
        command: ["/entrypoint.sh"]
        env:
        - name: HI168_ENV_TYPE
          value: {{ .Values.quantanexus.nginx.frontend.env.type | quote }}
        - name: HI168_ENV_URL_BASE
          {{- if .Values.global.useHttpIP  }}
          value: "http://{{ .Values.global.mgrDomainIP }}:{{ .Values.global.mgrDomainPort }}"
          {{- end }}
          {{- if not .Values.global.useHttpIP }}
          value: "https://{{ include "quantanexus.domainName" . }}"
          {{- end }}
        - name: HI168_SHOW_MODULE_LIST
          value: {{ .Values.quantanexus.nginx.frontend.env.moduleList | quote }}
        - name: HI168_COMMON_VAR_1
          {{- if .Values.global.useHttpIP  }}
          value: ""
          {{- end }}
          {{- if not .Values.global.useHttpIP  }}
          value: "upgrade-insecure-requests"
          {{- end }}
        - name: HI168_COMMON_VAR_2
          value: "HI168_COMMON_VAR_2"
        - name: HI168_COMMON_VAR_3
          value: "HI168_COMMON_VAR_3"
        volumeMounts:
        - name: app-code
          mountPath: /wwwroot
      containers:
      - name: nginx
        image: {{ .Values.global.registry }}/{{ .Values.quantanexus.nginx.repository }}:{{ .Values.quantanexus.nginx.tag }}
        imagePullPolicy: {{ .Values.quantanexus.app.imagePullPolicy }}
        ports:
        - containerPort: {{ .Values.quantanexus.nginx.port }}
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
        - name: app-code
          mountPath: /wwwroot
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-reverse-proxy-config
      - name: app-code
        emptyDir: {}
{{- end }}
