{{- if .Values.quantanexus.enabled  }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "quantanexus.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "quantanexus.labels" . | nindent 4 }}
data:
  prod.conf: |
    [options]
    ; disable listdb menu item
    list_db = False
    ; This is the password that allows database operations:
    ; admin_passwd = admin
    db_host = {{ .Release.Name }}-postgresql
    db_name = {{ .Values.postgresql.auth.database }}
    db_port = 5432
    db_user = {{ .Values.postgresql.auth.username }}
    db_password = {{ .Values.postgresql.auth.password }}
    addons_path = /var/lib/quantanexus/odoo/addons, /var/lib/quantanexus/addons, /var/lib/quantanexus/quantanexus-addons
    data_dir= /opt/data/quantanexus
    xmlrpc_port = 8069
    abc_domain_name = {{ .Values.global.domainName }}
    ; redis
    hwua_redis_enable=true
    hwua_redis_url={{ include "quantanexus.fullname" . }}-redis
    hwua_redis_port=6379
    hwua_redis_timeout=604800
    hwua_redis_password={{ include "redis.password" . }}
    hwua_redis_pool_max_connections=50
    hwua_redis_pool_timeout=300
    hwua_service_db=0
    ; memory
    limit_memory_hard = 10000000000
    limit_memory_soft = 8000000000
    max_cron_threads = {{ .Values.quantanexus.config.maxCronThreads }}
    workers          = {{ .Values.quantanexus.config.workers }}    
    system_install_namespace = {{ .Values.global.service_namespace }}
    module_image_center_enable = {{ .Values.quantanexus.config.moduleImageCenterEnable }}
    module_oss_manage_enable = {{ .Values.quantanexus.config.moduleOssManageEnable }}
    module_cloud_link_enable = {{ .Values.quantanexus.config.moduleCloudLinkEnable }}

  test.conf: |
    [options]
    ; disable listdb menu item
    list_db = False
    ; This is the password that allows database operations:
    ; admin_passwd = admin
    db_host = {{ .Release.Name }}-postgresql
    db_name = quantanexustest001
    db_port = 5432
    db_user = {{ .Values.postgresql.auth.username }}
    db_password = {{ .Values.postgresql.auth.password }}
    addons_path = /var/lib/quantanexus/odoo/addons, /var/lib/quantanexus/addons, /opt/runtime/quantanexus/quantanexus_addons
    data_dir= /opt/data/quantanexus
    xmlrpc_port = 8069
    ; redis
    hwua_redis_enable=true
    hwua_redis_url={{ include "quantanexus.fullname" . }}-redis
    hwua_redis_port=6379
    hwua_redis_timeout=604800
    hwua_redis_password={{ include "redis.password" . }}
    hwua_redis_pool_max_connections=50
    hwua_redis_pool_timeout=300
    hwua_service_db=0
    ; memory
    limit_memory_hard = 10000000000
    limit_memory_soft = 8000000000
    max_cron_threads = {{ .Values.quantanexus.config.maxCronThreads }}
    workers          = {{ .Values.quantanexus.config.workers }}    
    system_install_namespace = {{ .Values.global.service_namespace }}
    module_image_center_enable = {{ .Values.quantanexus.config.moduleImageCenterEnable }}
    module_oss_manage_enable = {{ .Values.quantanexus.config.moduleOssManageEnable }}
    module_cloud_link_enable = {{ .Values.quantanexus.config.moduleCloudLinkEnable }}

  pre-start.sh: |
    echo "quantanexus pre-start.sh called"
{{- end }}